# Generated by Django 3.0.8 on 2020-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='images/')),
                ('type', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student')], max_length=11)),
            ],
        ),
    ]
