# Generated by Django 3.0.8 on 2020-07-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_auto_20200716_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='employed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='unemployed_count',
            field=models.IntegerField(default=0),
        ),
    ]
