# Generated by Django 3.0.8 on 2020-07-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_auto_20200716_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_count', models.IntegerField(default=0)),
                ('unemployed_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='employed_count',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='unemployed_count',
        ),
    ]
