# Generated by Django 3.0.8 on 2020-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_auto_20200716_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentStatus',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='employed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='unemployed_count',
            field=models.IntegerField(default=0),
        ),
    ]
